apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: demoservice-sm
  namespace: monitoring
  labels:
    release: kp-stack
spec:
  selector:
    matchLabels:
      app: demoservice
  namespaceSelector:
    matchNames:
      - default     # where your service is deployed; change if different
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
